spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study_db
    username: hhjang
    password: hhjang1
    driver-class-name: com.mysql.jdbc.Driver
---

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

# 기동 시 program arguments에 넘어온 job.name 해당 값이 일치하는 job만 실행하는 옵션
# 값이 NONE일 경우 배치 실행을 막기 위함
#spring.batch.job.names: ${job.name:NONE}
#logging.level.org.springframework.batch: DEBUG
---
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---


